-   id: check-saludo
    name: saludo
    description: Manda un lindo saludo
    entry: check-saludo
    language: python
-   id: conventional-commits
    name: conventional-commits
    description: conventional-commits
    entry: conventional-commits
    language: python